import type { FaqItem } from "@/lib/corridorContent";

/**
 * Phase 5 — Regional banking & tax compliance repository.
 *
 * One record per corridor slug maps the regulatory body, legal authority,
 * withholding/exemption schedule, mandatory documentation, domestic clearing
 * network and a step-by-step realization-certificate checklist. Slugs without
 * a bespoke record receive the generic `DEFAULT_COMPLIANCE_GUIDE` so every
 * corridor page can render a complete, non-empty drawer.
 *
 * All copy is hedged informational guidance — never financial or tax advice —
 * and mirrors the editorial standards used in `lib/corridorContent.ts`.
 */

export interface ComplianceTaxRow {
  /** Taxpayer / transaction status, e.g. "PSEB-registered exporter". */
  status: string;
  /** Effective rate or treatment. */
  rate: string;
  /** Statutory basis, e.g. "FBR Section 154A". */
  basis: string;
}

export interface ComplianceChecklistStep {
  title: string;
  detail: string;
}

export interface ComplianceWarning {
  title: string;
  body: string;
}

export interface ComplianceGuide {
  /** Corridor slug this guide is bound to (e.g. `usd-to-pkr`). */
  slug: string;
  /** Drawer headline, e.g. "Pakistan Freelance Remittance & PSEB Tax Guide". */
  title: string;
  country: string;
  /** Primary regulator, e.g. "State Bank of Pakistan (SBP) — FEOD". */
  regulatoryBody: string;
  /** Governing statute / framework line. */
  legalAuthority: string;
  /** Domestic clearing rail(s) for the receiving country. */
  clearingNetwork: string;
  /** Mandatory documentation for substantiating the inward remittance. */
  documentation: string[];
  /** Lead sentence for the withholding / exemption table. */
  taxIntro: string;
  taxRows: ComplianceTaxRow[];
  checklistTitle: string;
  checklistSteps: ComplianceChecklistStep[];
  warning: ComplianceWarning;
  /** Regulatory FAQs merged into the page FAQPage JSON-LD and accordion. */
  faqs: FaqItem[];
}

const CRITICAL_WARNING: ComplianceWarning = {
  title: "Never route business proceeds through personal P2P crypto or third-party accounts",
  body:
    "Peer-to-peer crypto trades, friend-to-friend bank transfers and third-party wallet top-ups break the invoice-to-credit paper trail that every regulator above expects. Banks freeze accounts on AML / source-of-funds suspicion, and rebuilding the trail can take months. Keep every dollar on licensed rails with your name on both ends of the transfer.",
};

const CORRIDOR_GUIDES: Record<string, ComplianceGuide> = {
  "usd-to-pkr": {
    slug: "usd-to-pkr",
    title: "Pakistan Freelance Remittance & PSEB Tax Guide",
    country: "Pakistan",
    regulatoryBody:
      "State Bank of Pakistan (SBP) — Foreign Exchange Operations Department (FEOD)",
    legalAuthority:
      "SBP FEOD foreign-exchange instructions · Foreign Exchange Regulation Act, 1947 · Income Tax Ordinance, 2001 (FBR)",
    clearingNetwork:
      "1LINK / PayPak domestic clearing and SWIFT inward credit through SBP-authorised commercial banks",
    documentation: [
      "Proceeds Realization Certificate (PRC / e-PRC) generated by your domestic commercial bank — HBL, Meezan Bank or Bank Alfalah",
      "Bank credit advice / inward remittance statement quoting purpose code 9110",
      "Valid NTN with active FBR filer status (and PSEB export registration where claimed)",
      "Platform earning statement or client invoice evidencing export of IT/ITeS services",
    ],
    taxIntro:
      "Pakistan taxes export-of-services income under a presumptive regime. The regime you land in is decided by PSEB registration and filer status:",
    taxRows: [
      {
        status: "PSEB-registered IT/ITeS exporter (export proceeds)",
        rate: "0.25% concessionary final withholding tax",
        basis: "FBR Section 154A",
      },
      {
        status: "Individual / corporate filer outside the concession",
        rate: "Standard progressive slab rates on declared income",
        basis: "Income Tax Ordinance, 2001 — Slabs I–VI",
      },
      {
        status: "Non-filer",
        rate: "Higher withholding deducted at source on credit",
        basis: "FBR non-filer withholding provisions",
      },
    ],
    checklistTitle: "How to Obtain Your Realization Certificate (PRC / FIRC)",
    checklistSteps: [
      {
        title: "Receive the payout through a bank",
        detail:
          "Land the Upwork / Fiverr withdrawal in your PKR or foreign-currency account at HBL, Meezan, Alfalah or another SBP-authorised dealer — never through an informal hundi-style operator.",
      },
      {
        title: "Quote purpose code 9110",
        detail:
          "Instruct the bank to credit the inward remittance under purpose code 9110 — Telecommunication / Computer Information Services — the correct narration for IT and ITeS freelance exports.",
      },
      {
        title: "Generate the e-PRC",
        detail:
          "Ask the branch or open the bank's export-remittance portal and generate the Proceeds Realization Certificate (PRC / e-PRC) for the credited amount; most banks issue it the same banking day.",
      },
      {
        title: "Match the certificate to the invoice",
        detail:
          "Keep the PRC tied to the platform statement and the client invoice — PSEB and FBR reviews cross-check amounts, dates and the beneficiary name.",
      },
      {
        title: "File with the certificate attached",
        detail:
          "Attach the PRC to your concessionary withholding claim under Section 154A and to your PSEB export declarations so the 0.25% treatment is substantiated.",
      },
    ],
    warning: CRITICAL_WARNING,
    faqs: [
      {
        q: "Do I have to pay tax on Upwork withdrawals in Pakistan?",
        a: "Yes — export-of-services earnings are taxable in Pakistan. PSEB-registered IT/ITeS exporters can attract a 0.25% concessionary final withholding on qualifying proceeds under FBR Section 154A, while the standard individual slabs apply otherwise. Filers are deducted at lower rates than non-filers, so keep your FBR profile active and confirm your position with a chartered accountant.",
      },
      {
        q: "How do I claim a PRC from my bank?",
        a: "Once the USD credit lands, ask HBL, Meezan Bank, Bank Alfalah or your other SBP-authorised bank to issue a Proceeds Realization Certificate (PRC / e-PRC) against purpose code 9110. Most banks generate it same-day through the branch or the export-remittance web portal — keep the PDF with your invoice.",
      },
      {
        q: "Which purpose code do freelance IT exports use?",
        a: "Purpose code 9110 — Telecommunication / Computer Information Services — is the inward-remittance narration for software, design, SEO, content and other IT/ITeS freelance exports received into Pakistan.",
      },
    ],
  },

  "usd-to-inr": {
    slug: "usd-to-inr",
    title: "India Inward Remittance, FIRC & GST Exemption Guide",
    country: "India",
    regulatoryBody:
      "Reserve Bank of India (RBI) under FEMA (Foreign Exchange Management Act, 1999)",
    legalAuthority:
      "FEMA, 1999 · RBI Master Direction on Export of Goods and Services · CGST Act, 2017 · Income-tax Act, 1961",
    clearingNetwork:
      "NEFT / IMPS / RTGS domestic settlement through Authorised Dealer Category-I (AD-I) banks",
    documentation: [
      "Foreign Inward Remittance Certificate (FIRC) issued by your AD-I bank",
      "Foreign Inward Remittance Statement (FIRS) with the inward remittance details",
      "GST registration plus a valid Letter of Undertaking (LUT) for zero-rated export of services",
      "Form 67 filing where foreign tax credit is claimed, plus the invoice trail",
    ],
    taxIntro:
      "Inward remittances for services are taxed under normal presumptive or slab rules, while GST turns on your LUT position:",
    taxRows: [
      {
        status: "Export of services with a valid LUT on file",
        rate: "Zero-rated — 0% GST",
        basis: "CGST Act, 2017 §16(3) with Rule 96A (Letter of Undertaking)",
      },
      {
        status: "Export of services without an LUT",
        rate: "IGST paid upfront, refundable on realization",
        basis: "CGST Act, 2017 §16(1)",
      },
      {
        status: "Professional / technical freelance income",
        rate: "Presumptive taxation (§44ADA where eligible) or slab rates; §194J TDS applies to Indian payers",
        basis: "Income-tax Act, 1961",
      },
      {
        status: "Foreign tax suffered on the payout",
        rate: "Credit claimed against Indian tax liability",
        basis: "Income-tax Act Form 67 (foreign tax credit)",
      },
    ],
    checklistTitle: "How to Obtain Your Realization Certificate (PRC / FIRC)",
    checklistSteps: [
      {
        title: "Route the payout through your AD-I bank",
        detail:
          "Receive the USD withdrawal into your savings or current account at an Authorised Dealer Category-I bank (SBI, HDFC, ICICI, Axis and peers) with complete exporter / purpose narration.",
      },
      {
        title: "Confirm the credit in the FIRS",
        detail:
          "The AD-I bank posts every inward remittance in the Foreign Inward Remittance Statement (FIRS); check the amount, remitter and purpose match your invoice before filing anything.",
      },
      {
        title: "Request the FIRC",
        detail:
          "Ask your branch or trade-desk for the Foreign Inward Remittance Certificate (FIRC) — many banks now issue it electronically against the FIRS entry.",
      },
      {
        title: "Keep FEMA substantiation ready",
        detail:
          "Retain the invoice, bank advice and FIRC/FIRS for at least six assessment years; FEMA requires proof that export proceeds were realized through eligible channels.",
      },
      {
        title: "Pair the certificate with your GST and income filings",
        detail:
          "File GSTR-1/GSTR-3B as a zero-rated supply with the LUT reference, and attach Form 67 for any foreign tax credit — the FIRC supports both.",
      },
    ],
    warning: CRITICAL_WARNING,
    faqs: [
      {
        q: "Is GST zero-rated on freelance export of services from India?",
        a: "Yes, when you file a valid Letter of Undertaking (LUT) with the tax authorities you may export services zero-rated — 0% GST — without paying IGST first. Without an LUT you pay IGST upfront and claim a refund once the remittance is realized.",
      },
      {
        q: "What is a FIRC and do I still need one?",
        a: "The Foreign Inward Remittance Certificate (FIRC) is your bank's proof that foreign currency was actually realized in your account; the FIRS statement records each inward entry. FEMA substantiation, foreign tax credit claims and lender checks still rely on them, so request both from your AD-I bank.",
      },
      {
        q: "How do I claim foreign tax credit with Form 67?",
        a: "If tax was withheld on the payout abroad, file Form 67 in the relevant assessment year with the foreign tax certificate and your FIRC/FIRS details; the credit offsets your Indian liability subject to the double-taxation agreement.",
      },
    ],
  },

  "usd-to-php": {
    slug: "usd-to-php",
    title: "Philippines Cross-Border Freelance Remittance Guide",
    country: "Philippines",
    regulatoryBody: "Bangko Sentral ng Pilipinas (BSP)",
    legalAuthority:
      "BSP circulars on cross-border transfers and remittance limits · National Internal Revenue Code (NIRC) — Bureau of Internal Revenue (BIR)",
    clearingNetwork:
      "PESONet and InstaPay domestic rails to BDO Unibank, BPI and UnionBank, plus GCash / Maya wallet cash-in under BSP rules",
    documentation: [
      "Bank inward-remittance advice or statement showing the remitter and purpose",
      "BIR Form 1701Q (quarterly) and the annual return covering foreign-source income",
      "BIR Form 2307 / Certificate of Creditable Tax Withheld where a local payee withheld",
      "TIN and BIR-registered receipt / invoice trail for the engagement",
    ],
    taxIntro:
      "Resident Filipino earners are taxed on income earned while resident, whether the client is abroad or local:",
    taxRows: [
      {
        status: "Resident professional / self-employed earner",
        rate: "Graduated income-tax rates on net taxable income",
        basis: "NIRC §24(A) — BIR Form 1701Q / 1701",
      },
      {
        status: "Withheld by a local payor on service fees",
        rate: "Expanded withholding tax credited via BIR Form 2307",
        basis: "NIRC §57 / BIR RR 11-2018",
      },
      {
        status: "Cross-border payout with foreign tax suffered",
        rate: "Foreign tax credit claimed against PH tax due",
        basis: "NIRC §34(D) and applicable tax treaties",
      },
    ],
    checklistTitle: "How to Obtain Your Realization Certificate (PRC / FIRC)",
    checklistSteps: [
      {
        title: "Land the payout in a supervised account",
        detail:
          "Credit the USD withdrawal to BDO Unibank, BPI, UnionBank or a BSP-supervised e-wallet (GCash / Maya) that supports inbound foreign transfers under your own TIN-matched name.",
      },
      {
        title: "Capture the inward remittance advice",
        detail:
          "Download the bank credit advice or wallet transaction detail showing the remitter, purpose and USD amount — this is your realization evidence for BIR.",
      },
      {
        title: "Observe wallet limits before you sweep",
        detail:
          "GCash and Maya carry per-transaction and monthly caps plus cash-out fees; large payouts almost always clear cheaper into a bank account first.",
      },
      {
        title: "Report quarterly on Form 1701Q",
        detail:
          "Declare foreign-source freelance income in your quarterly BIR Form 1701Q and reconcile it against the inward advices each cut-off.",
      },
      {
        title: "Claim credits with Form 2307",
        detail:
          "Where a payor withheld on your behalf, collect BIR Form 2307 and attach it to your annual return so the credit is not lost.",
      },
    ],
    warning: CRITICAL_WARNING,
    faqs: [
      {
        q: "Do I have to report Upwork or Fiverr earnings in my BIR return?",
        a: "Yes — income from services rendered while you are a Philippine resident is taxable whether the client is abroad or local. Report it on BIR Form 1701Q quarterly and the annual return, and keep the inward remittance advices as substantiation.",
      },
      {
        q: "Can I receive my payout directly into GCash or Maya?",
        a: "BSP-supervised wallets accept qualifying inbound transfers, but per-transaction caps, cash-in fees and slower USD-to-peso floats often make a bank account cheaper for large invoices. Slide the calculator above to compare the peso you actually keep.",
      },
    ],
  },

  "usd-to-gbp": {
    slug: "usd-to-gbp",
    title: "United Kingdom Freelance Remittance & Self Assessment Guide",
    country: "United Kingdom",
    regulatoryBody:
      "HM Revenue & Customs (HMRC); payment rails operated under Bank of England / Pay.UK oversight",
    legalAuthority:
      "Income Tax Act, 2007 (Self Assessment) · Payment Services Regulations, 2017 · UK–US double taxation agreement",
    clearingNetwork:
      "Faster Payments (near real-time), CHAPS (same-day high value) and Bacs, with SWIFT inbound USD conversion",
    documentation: [
      "UK bank credit advice with sort code / IBAN and the remitter reference",
      "Platform earning statements (Upwork / Fiverr) and client invoices",
      "Self Assessment records using one consistent FX conversion method",
      "Evidence of any foreign tax deducted for treaty-relief claims",
    ],
    taxIntro:
      "UK residents report worldwide freelance income through Self Assessment:",
    taxRows: [
      {
        status: "Side-line / small trading income",
        rate: "£1,000 Trading Allowance before tax applies",
        basis: "Income Tax Act, 2005 — Trading Allowance",
      },
      {
        status: "Self-employed freelancer above the allowance",
        rate: "Graduated income-tax bands plus Class 4 NICs above the profits threshold",
        basis: "Income Tax Act, 2007 Part 4 / NICs Act, 2015",
      },
      {
        status: "VAT-registered or VAT-eligible supplier",
        rate: "Place-of-supply rules determine UK VAT treatment for B2B services",
        basis: "VATA, 1994 & HMRC place-of-supply guidance",
      },
    ],
    checklistTitle: "How to Document Your Inward Remittance",
    checklistSteps: [
      {
        title: "Receive to a UK account",
        detail:
          "Land the USD wire in your UK account — many banks open a USD sub-account so you can time the conversion instead of taking the default desk rate.",
      },
      {
        title: "Keep the credit advice",
        detail:
          "Save the bank credit advice or online statement line showing remitter, amount and date; it anchors the sterling figure you declare.",
      },
      {
        title: "Convert with one consistent method",
        detail:
          "Record the spot or monthly-average rate you used and apply it consistently — HMRC accepts a reasonable, repeatable method across the year.",
      },
      {
        title: "Reconcile against platform statements",
        detail:
          "Match the wire to the Upwork / Fiverr payout statement so gross earnings, platform fees and net remittance line up.",
      },
      {
        title: "File through Self Assessment",
        detail:
          "Report the income in your tax return (online by 31 January) and keep the remittance file for at least five years.",
      },
    ],
    warning: CRITICAL_WARNING,
    faqs: [
      {
        q: "Do UK freelancers pay tax on income from overseas clients?",
        a: "Yes — worldwide income from self-employment is taxable in the UK through Self Assessment. The £1,000 Trading Allowance can cover small-scale earnings before the marginal bands (and Class 4 NICs) apply.",
      },
      {
        q: "Which rail should I choose for large payouts?",
        a: "Faster Payments handles most amounts in seconds; CHAPS is the same-day route for very large single wires. The fee table on this page prices both against spread-light alternatives so the crossover in pounds is explicit.",
      },
    ],
  },

  "usd-to-eur": {
    slug: "usd-to-eur",
    title: "Eurozone Freelance Remittance, SEPA & VAT Guide",
    country: "Eurozone",
    regulatoryBody:
      "European Central Bank (SEPA regulation) and national competent authorities (e.g. ACPR, BaFin)",
    legalAuthority:
      "Regulation (EU) No 260/2012 (SEPA) · Directive 2015/2366 (PSD2) · Council Directive 2006/112/EC (VAT)",
    clearingNetwork:
      "SEPA Credit Transfer (next business day) and SEPA Instant (seconds), fed by SWIFT inbound USD conversion",
    documentation: [
      "IBAN + BIC credit advice from the receiving euro account",
      "Client invoices and platform statements evidencing the service",
      "ECB / EBA reference-rate record used to convert USD income",
      "VAT evidence (LUT-equivalent, OSS or reverse-charge notes) where applicable",
    ],
    taxIntro:
      "Eurozone residents are taxed on worldwide freelance income; VAT treatment depends on the client's location:",
    taxRows: [
      {
        status: "B2B digital services to another EU business",
        rate: "VAT reverse charge — accounted for by the client",
        basis: "Council Directive 2006/112/EC Art. 44 / 196",
      },
      {
        status: "Resident freelance income",
        rate: "Progressive national income-tax rates on worldwide income",
        basis: "Member-state income tax codes",
      },
      {
        status: "USD-to-EUR conversion for reporting",
        rate: "ECB / EBA reference rate is the accepted conversion basis",
        basis: "ECB reference-rate methodology",
      },
    ],
    checklistTitle: "How to Document Your Inward Remittance",
    checklistSteps: [
      {
        title: "Provide a complete IBAN and BIC",
        detail:
          "Send your euro account's IBAN plus BIC to the payer and double-check the beneficiary address — structured SWIFT field pruning on US-origin wires is a common stalling point.",
      },
      {
        title: "Request the incoming-FX advice",
        detail:
          "Ask for the credit advice after conversion; eurozone banks often levy a small incoming-conversion memo you should capture for your records.",
      },
      {
        title: "Record the conversion reference",
        detail:
          "Note the ECB / EBA reference rate (or your consistent bank rate) used for the USD-to-EUR conversion alongside the invoice.",
      },
      {
        title: "Confirm the SEPA leg",
        detail:
          "Once converted, SEPA Credit Transfer settles next business day and SEPA Instant in seconds — verify the funds left the float before treating them as spendable.",
      },
      {
        title: "File VAT and income correctly",
        detail:
          "Apply reverse charge (or your local B2B treatment) on the invoice, then declare the euro income on your return using the recorded reference rate.",
      },
    ],
    warning: CRITICAL_WARNING,
    faqs: [
      {
        q: "Do I pay tax on Upwork income as a Eurozone resident?",
        a: "Yes — freelance income is taxable where you are established, on your worldwide income. Keep the invoice, conversion rate and bank credit advice together so the euro figure you declare is fully substantiated.",
      },
      {
        q: "Is the SEPA leg or the FX conversion the real cost?",
        a: "SEPA itself is nearly free and fast; the leak is almost always the USD-to-EUR spread. At the corridor reference rate a 2% spread on $10,000 outruns any flat fee in the dataset — which is exactly what the ranked breakdown above measures.",
      },
    ],
  },

  "usd-to-brl": {
    slug: "usd-to-brl",
    title: "Brazil Freelance Remittance, IOF & PIX Guide",
    country: "Brazil",
    regulatoryBody:
      "Banco Central do Brasil (BCB) and Receita Federal do Brasil",
    legalAuthority:
      "Law No. 14,286/2021 (FX framework) · IOF Law No. 14,057/2020 · Income Tax Law (IRPF/IRPJ) · PIX resolution BCB",
    clearingNetwork:
      "PIX (instant, 24/7) plus TED / DOC bank transfers, funded by SWIFT inbound USD conversion",
    documentation: [
      "CCP / exchange-contract reference and the bank conversion advice",
      "Client invoice and platform statement evidencing export of services",
      "PIX or TED credit proof aligned with declared receipts",
      "CPF / CNPJ and an up-to-date cadastro for large-transfer monitoring",
    ],
    taxIntro:
      "Two taxes shadow every conversion — IOF on the FX operation and income tax on foreign earnings:",
    taxRows: [
      {
        status: "Standard foreign-exchange conversion",
        rate: "IOF typically 0.38% (rates vary by operation type)",
        basis: "IOF Law No. 14,057/2020 and decree schedules",
      },
      {
        status: "Resident with foreign-source income",
        rate: "Progressive IRPF rates on worldwide income (annual adjustment)",
        basis: "Lei 9,250/1995 · IRPF tables",
      },
      {
        status: "Conversion inside a licensed operator's spread",
        rate: "Compare gross-to-net — several providers re-quote IOF inside the spread",
        basis: "BCB-licensed institution rate transparency rules",
      },
    ],
    checklistTitle: "How to Document Your Inward Remittance",
    checklistSteps: [
      {
        title: "Convert through a licensed operator",
        detail:
          "Use a BCB-licensed bank or payment institution (instituição de pagamento licenciada) — informal currency shops are not compliant venues for reportable income.",
      },
      {
        title: "Keep the conversion record",
        detail:
          "Save the exchange contract (contrato de câmbio) or the bank's conversion advice showing USD in, BRL out, rate and IOF charged.",
      },
      {
        title: "Receive the BRL via PIX",
        detail:
          "Let the operator settle to your PIX key or account — the domestic leg clears in seconds; the USD-to-operator float is the scheduling cost.",
      },
      {
        title: "Reconcile receipts with declarations",
        detail:
          "Match the incoming TED/PIX to your declared receipts so IRPF filings and bank narratives agree during monitoring thresholds.",
      },
      {
        title: "Substantiate export-of-services evidence",
        detail:
          "Retain the client invoice, platform statement and conversion proof together; Receita audits of online earners focus on undeclared foreign income.",
      },
    ],
    warning: CRITICAL_WARNING,
    faqs: [
      {
        q: "Is IOF included in the fees shown on this page?",
        a: "No — IOF is a country-level deduction layered on top of the modeled fixed fee and FX spread. Treat the verdict as a relative channel ranking and add IOF separately for absolute tax planning.",
      },
      {
        q: "Do I need to declare remittances from abroad in Brazil?",
        a: "Yes — resident worldwide income is taxable under IRPF, and funds must enter through licensed operators so the paper trail exists. Keep the conversion advice and the PIX/TED credit paired with your invoice.",
      },
    ],
  },

  "usd-to-ngn": {
    slug: "usd-to-ngn",
    title: "Nigeria Freelance Remittance, CBN & Tax Guide",
    country: "Nigeria",
    regulatoryBody:
      "Central Bank of Nigeria (CBN); Federal Inland Revenue Service (FIRS) and state internal revenue boards",
    legalAuthority:
      "CBN Foreign Exchange Manual and window guidance · Companies Income Tax Act, 2004 · Personal Income Tax Act, 2020 (as amended by the Finance Act)",
    clearingNetwork:
      "NIBSS Instant Payment (NIP) to Naira accounts, NEFT / RTGS for larger legs, and SWIFT inbound USD at official windows",
    documentation: [
      "BVN-linked bank account with consistent occupation and KYC details",
      "Client invoice or platform statement evidencing the service export",
      "Bank credit advice / inward remittance advice at the official window",
      "Tax identification (TIN / VAT registration where applicable) and returns",
    ],
    taxIntro:
      "Foreign inbound earnings are taxable income regardless of the rail they arrive on:",
    taxRows: [
      {
        status: "Self-employed resident earner",
        rate: "Progressive personal income tax of your state plus applicable levies",
        basis: "Personal Income Tax Act, 2020 (as amended)",
      },
      {
        status: "Taxable services supplied in Nigeria",
        rate: "7.5% VAT on taxable services",
        basis: "Value Added Tax Act, 1993 (as amended by Finance Act)",
      },
      {
        status: "Conversion at the official window",
        rate: "Convert at the CBN-validated rate for the year when reporting income",
        basis: "CBN window / NAFEM guidance",
      },
    ],
    checklistTitle: "How to Document Your Inward Remittance",
    checklistSteps: [
      {
        title: "Use a CBN-sanctioned channel",
        detail:
          "Receive the USD through an official window or licensed fintech rail — parallel-rate arbitrage breaches CBN FX rules and is never a compliant route for reportable income.",
      },
      {
        title: "Match your KYC narrative",
        detail:
          "Keep BVN, declared occupation and transfer narratives consistent; wallet rails freeze accounts whose declared profile contradicts transaction descriptions.",
      },
      {
        title: "Capture the credit advice",
        detail:
          "Save the bank or fintech credit advice showing remitter, purpose and the naira credited at the official rate.",
      },
      {
        title: "Receive via NIP for speed",
        detail:
          "Licensed fintech wallets and banks credit naira over NIBSS Instant Payment the same day once USD is matched to your account.",
      },
      {
        title: "File returns that substantiate the story",
        detail:
          "Declare the foreign income with the invoice and credit advice attached — unexplained foreign inflows draw scrutiny under AML frameworks.",
      },
    ],
    warning: CRITICAL_WARNING,
    faqs: [
      {
        q: "Is it legal to exploit the gap between official and parallel rates?",
        a: "No — parallel-rate arbitrage can breach CBN foreign-exchange rules. Use only CBN-sanctioned conversion routes, convert at the validated rate for tax reporting, and keep every credit advice on file.",
      },
      {
        q: "Why does my bank ask so many questions about a US wire?",
        a: "Source-of-funds and beneficiary verification are standard AML steps for inbound freelancer proceeds. Respond with the invoice, platform statement and your KYC details — a complete narrative releases the hold fastest.",
      },
    ],
  },

  "usd-to-bdt": {
    slug: "usd-to-bdt",
    title: "Bangladesh Freelance Remittance, BEFTN & Tax Guide",
    country: "Bangladesh",
    regulatoryBody: "Bangladesh Bank; National Board of Revenue (NBR)",
    legalAuthority:
      "Foreign Exchange Regulation Act, 1947 · Income Tax Act, 2023 · Money Laundering Prevention Act, 2012",
    clearingNetwork:
      "BEFTN and RTGS for bank legs, mobile financial services (bKash, Nagad) for wallet sweeps, SWIFT inbound USD",
    documentation: [
      "Bank inward remittance advice citing the remitter and purpose",
      "Source-of-earning attestation (e-banking records, platform invoice)",
      "TIN and tax return substantiating the foreign income",
      "Aggregator / wallet sweep statements kept with the USD credit record",
    ],
    taxIntro:
      "Remittance income is taxable; formal rails also unlock incentive schemes:",
    taxRows: [
      {
        status: "Bank-channeled inward remittance (qualifying wage earners)",
        rate: "Cash incentive of up to 2.5% on qualifying remittances (scheme terms apply)",
        basis: "Bangladesh Bank remittance incentive scheme",
      },
      {
        status: "Freelance export-of-services income",
        rate: "Taxed at applicable individual rates — taxable regardless of rail",
        basis: "Income Tax Act, 2023",
      },
      {
        status: "Wallet sweep after conversion",
        rate: "Wallet cash-out fees and caps modeled as fixed cost in the audit",
        basis: "MFS operator schedules under Bangladesh Bank licensing",
      },
    ],
    checklistTitle: "How to Document Your Inward Remittance",
    checklistSteps: [
      {
        title: "Receive through a bank first",
        detail:
          "Land the USD in a bank account at an authorized dealer so the inward remittance is registered — formal rails are the precondition for cash incentives.",
      },
      {
        title: "Cite the purpose clearly",
        detail:
          "Give the bank the service-export narration and your platform/client invoice so the credit clears without a compliance stall.",
      },
      {
        title: "Keep the inward advice",
        detail:
          "Download the inward remittance advice or e-statement line; it is your proof for both tax filings and incentive claims.",
      },
      {
        title: "Sweep to wallets deliberately",
        detail:
          "bKash / Nagad sweeps are near-instant locally but add a settlement float on the USD leg — prefer them for small amounts, banks for large invoices.",
      },
      {
        title: "File with substantiation",
        detail:
          "Declare the income with TIN-linked returns and keep the bank, invoice and wallet statements together to explain every inflow.",
      },
    ],
    warning: CRITICAL_WARNING,
    faqs: [
      {
        q: "Is there an incentive for receiving remittances in Bangladesh?",
        a: "Yes — bank-channeled inward remittances have historically carried a cash incentive (commonly up to 2.5% on qualifying receipts), but the scheme requires formal rails and proper documentation, so keep every inward advice.",
      },
      {
        q: "Do I pay tax on freelance earnings from abroad?",
        a: "Yes — freelance income is taxable in Bangladesh whether it arrives by bank or wallet. File with your TIN, attach the inward advices, and keep the source-of-earning attestation ready for KYC reviews.",
      },
    ],
  },

  "usd-to-egp": {
    slug: "usd-to-egp",
    title: "Egypt Freelance Remittance, CBE & Tax Card Guide",
    country: "Egypt",
    regulatoryBody:
      "Central Bank of Egypt (CBE); Egyptian Tax Authority (ETA)",
    legalAuthority:
      "CBE foreign-exchange and banking circulars · Income Tax Law No. 91 of 2005 (as amended) · Value Added Tax Law No. 67 of 2016",
    clearingNetwork:
      "National instant payments — IR-CT and InstaPay (near real-time) — plus SWIFT inbound USD with CBE conversion policy",
    documentation: [
      "Bank inward credit advice with the remitter and purpose narrated",
      "Client invoice or platform statement for the service rendered",
      "Tax card (بطاقة ضريبية) and declared turnover for the activity",
      "Passport / national ID matching the beneficiary name on the wire",
    ],
    taxIntro:
      "Egypt taxes residents on worldwide income; compliance starts with a valid tax profile:",
    taxRows: [
      {
        status: "Resident with worldwide income",
        rate: "Progressive personal income tax up to 22.5%",
        basis: "Income Tax Law No. 91 of 2005 (as amended)",
      },
      {
        status: "Service activity conducted in Egypt",
        rate: "Tax card registration and turnover declaration required",
        basis: "Egyptian Tax Authority tax-card rules",
      },
      {
        status: "USD converted at the bank",
        rate: "Report conversion at CBE-published rates to avoid revaluation disputes",
        basis: "CBE published reference rates",
      },
    ],
    checklistTitle: "How to Document Your Inward Remittance",
    checklistSteps: [
      {
        title: "Receive into a named bank account",
        detail:
          "Credit the USD wire to your account — names must match across passport, beneficiary and wallet registrations or the transfer will be reversed.",
      },
      {
        title: "Narrate the purpose",
        detail:
          "Instruct the remitter to cite freelance / consulting services and keep the commercial invoice attached; demanding branches use the narration for compliance screening.",
      },
      {
        title: "Request the credit advice",
        detail:
          "Save the bank's foreign-currency receipt advice and the EGP conversion slip showing the official rate applied.",
      },
      {
        title: "Convert officially",
        detail:
          "Convert through the bank or a licensed dealer — CBE conversion policy governs reportable receipts, and informal venues create filing gaps.",
      },
      {
        title: "Declare against your tax card",
        detail:
          "Reconcile each credit with the turnover declared on your tax card so assessments do not reopen the conversion.",
      },
    ],
    warning: CRITICAL_WARNING,
    faqs: [
      {
        q: "Do Egyptian banks charge an extra fee on US wires?",
        a: "Incoming SWIFT entries sometimes carry an incoming-credit memo deducted at source. The fixed-fee column in the audit models the visible part — the conversion spread is the silent one, which is why the effective rate matters more than the quoted fee.",
      },
      {
        q: "Can I hold the USD instead of converting?",
        a: "Some accounts permit foreign-currency receipts under CBE rules; when you do convert, keep the bank conversion slip at the official rate so your tax filings and bank records agree.",
      },
    ],
  },

  "usd-to-zar": {
    slug: "usd-to-zar",
    title: "South Africa Freelance Remittance, SARB & SARS Guide",
    country: "South Africa",
    regulatoryBody:
      "South African Reserve Bank (SARB) — Financial Surveillance; South African Revenue Service (SARS)",
    legalAuthority:
      "Currency and Exchanges Act No. 9 of 1933 (SARB Financial Surveillance) · Income Tax Act No. 58 of 1962 · Tax Administration Act No. 28 of 2011",
    clearingNetwork:
      "SARIE / EFT for domestic distribution and PayShap for near-instant sends, funded by SWIFT inbound USD at authorised dealers",
    documentation: [
      "Authorised-dealer credit advice with the repatriation narrative (Form A lineage where applicable)",
      "Client invoice or platform statement evidencing the export of services",
      "Consistent rand conversion record (SARB-adjacent rate) for the tax year",
      "SARS return substantiating the foreign income against e-wallet / bank statements",
    ],
    taxIntro:
      "Residents are taxed on worldwide income; allowance rules govern outward flows, not inward earnings:",
    taxRows: [
      {
        status: "Resident with worldwide income",
        rate: "Progressive rates 18%–45%, plus 1%–3% surcharge above the tax thresholds",
        basis: "Income Tax Act No. 58 of 1962 §§5 and 8",
      },
      {
        status: "Inward repatriation of freelancer earnings",
        rate: "Compliance-clean route — declare as income, not as a foreign liability",
        basis: "SARB Currency & Exchanges Manual / authorised dealer guidance",
      },
      {
        status: "Outward sweep of funds (if you re-export later)",
        rate: "Single Discretionary Allowance R1m p.a.; Foreign Investment Allowance up to R10m p.a. (limits and tax-clearance rules apply)",
        basis: "SARB Currency & Exchanges Manual allowances",
      },
    ],
    checklistTitle: "How to Document Your Inward Remittance",
    checklistSteps: [
      {
        title: "Bank at an authorised dealer",
        detail:
          "Receive the USD through a bank authorised to deal in foreign exchange; deposits without a repatriation narrative risk being treated as a foreign liability.",
      },
      {
        title: "State the repatriation narrative",
        detail:
          "Mark the receipt as export-of-services proceeds (Form A lineage where the dealer requires it) so Financial Surveillance sees a clean inward flow.",
      },
      {
        title: "Keep the SWIFT advice",
        detail:
          "Save the SWIFT MT103 or bank credit advice plus the conversion slip; SARS increasingly reconciles declared foreign income against bank evidence.",
      },
      {
        title: "Choose your conversion timing",
        detail:
          "Residents may generally keep funds offshore or convert locally — the audit's effective-rate column is your decision input, not a legal requirement.",
      },
      {
        title: "Declare consistently in rand",
        detail:
          "Report income at a consistent rate for the year in your ITR12 so assessments stay predictable across the assessment cycle.",
      },
    ],
    warning: CRITICAL_WARNING,
    faqs: [
      {
        q: "Must South African residents convert USD earnings immediately?",
        a: "No — the rules govern what may sit offshore and how earnings are declared, not an instant conversion mandate. If you keep USD, record the conversion rate you eventually use and keep the SWIFT advice on file.",
      },
      {
        q: "Do I declare foreign freelance income to SARS?",
        a: "Yes — residents are taxed on worldwide income. Declare the receipts in consistent rand terms with your invoice and bank advice attached; the single discretionary allowance limits outward transfers, not what you must report inward.",
      },
    ],
  },
};

const DEFAULT_COMPLIANCE_GUIDE: ComplianceGuide = {
  slug: "(generic)",
  title: "Cross-Border Freelance Remittance Compliance Guide",
  country: "destination market",
  regulatoryBody:
    "The destination country's central bank and national revenue authority",
  legalAuthority:
    "Foreign-exchange control rules and national income-tax law of the receiving jurisdiction",
  clearingNetwork:
    "Inbound SWIFT converted by an authorised dealer, then distributed on the domestic clearing rail of the receiving country",
  documentation: [
    "Bank inward credit advice quoting remitter, purpose and amount",
    "Client invoice or platform statement evidencing export of services",
    "Foreign inward remittance certificate or equivalent issued by the receiving bank",
    "Completed tax returns substantiating the declared foreign income",
  ],
  taxIntro:
    "Cross-border freelance proceeds are normally taxable in the receiving jurisdiction under one of these treatments:",
  taxRows: [
    {
      status: "Resident recipient of foreign-source service income",
      rate: "Taxed at ordinary resident rates (slabs or presumptive regimes)",
      basis: "National income-tax law of the receiving country",
    },
    {
      status: "Withholding applied by the paying platform",
      rate: "Creditable against local tax where a treaty or certificate applies",
      basis: "Double-taxation agreement / domestic withholding provisions",
    },
    {
      status: "FX conversion at the receiving bank",
      rate: "Not a tax — bank spread and clearing fees still reduce the net",
      basis: "Provider rate card (see the ranked breakdown above)",
    },
  ],
  checklistTitle: "How to Document Your Inward Remittance",
  checklistSteps: [
    {
      title: "Receive through a licensed institution",
      detail:
        "Land the payout in a bank or licensed money-service provider account held in your own name so the transfer stays on reportable rails.",
    },
    {
      title: "Cite the purpose",
      detail:
        "Ask the remitter to narrate the payment as freelance / consulting service proceeds — vague narratives trigger avoidable compliance holds.",
    },
    {
      title: "Capture the credit advice",
      detail:
        "Download the inward credit advice or remittance statement; it is the anchor document for both tax filings and dispute resolution.",
    },
    {
      title: "Keep the invoice trail",
      detail:
        "Pair every credit with the client invoice and platform statement so amounts, dates and counterparties reconcile end to end.",
    },
    {
      title: "File with the evidence attached",
      detail:
        "Declare the income on your local return with the conversion record attached, and retain the full file for the statutory limitation period.",
    },
  ],
  warning: CRITICAL_WARNING,
  faqs: [
    {
      q: "Do I have to pay tax on freelance income from abroad?",
      a: "Almost always yes — residents are generally taxed on worldwide service income regardless of which platform or rail delivered it. The exact rate depends on your local regime and filer status, so confirm treatment with a local accountant.",
    },
    {
      q: "What documents should I keep for every remittance?",
      a: "The invoice, the platform payout statement, the bank inward credit advice and any remittance certificate the receiving bank issues. Together they prove source, amount and timing — the three things auditors ask for first.",
    },
  ],
};

/**
 * Resolves the compliance guide for a corridor slug; unknown slugs fall back
 * to a complete generic record so the UI never renders an empty drawer.
 */
export function getComplianceGuide(slug: string): ComplianceGuide {
  return CORRIDOR_GUIDES[slug] ?? { ...DEFAULT_COMPLIANCE_GUIDE, slug };
}

/** True when the slug has a bespoke (country-specific) compliance record. */
export function hasComplianceGuide(slug: string): boolean {
  return Object.hasOwn(CORRIDOR_GUIDES, slug);
}

/** Corridor slugs with bespoke regulatory content (used by the audit script). */
export function getComplianceGuideSlugs(): string[] {
  return Object.keys(CORRIDOR_GUIDES);
}
